# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyp9se5U8ZwfU-henl-HejhRLpYN4ahC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load in Data Set
df = pd.read_csv("Jewelry_Dataset.csv")

df.columns = [
    "Order_Datetime",
    "Order_ID",
    "Product_ID",
    "SKU_Quality",
    "Category_ID",
    "Category",
    "Brand_ID",
    "Price_USD",
    "User_ID",
    "Target_Gender",
    "Main_Color",
    "Main_Metal",
    "Main_Gem",

]

df.head()

df.info()

print(df.shape)
print(df.dtypes)
print(df.isnull().sum())
print(df["Price_USD"].describe())

# Price distribution
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sns.histplot(df["Price_USD"], bins=60, ax=axes[0])
axes[0].set_title("Price distribution")
sns.histplot(np.log1p(df["Price_USD"]), bins=60, ax=axes[1])
axes[1].set_title("Log-price distribution")
plt.tight_layout(); plt.show()

# ── Price by categorical columns ─────────────────────────
for col in ["Category", "Main_Metal", "Main_Gem", "Main_Color", "Target_Gender"]:
    plt.figure(figsize=(12, 4))
    order = df.groupby(col)["Price_USD"].median().sort_values(ascending=False).index
    sns.boxplot(data=df, x=col, y="Price_USD", order=order)
    plt.yscale("log")
    plt.title(f"Price by {col}")
    plt.xticks(rotation=35, ha="right")
    plt.tight_layout(); plt.show()

# ── SKU_Quality vs Price ──────────────────────────────────
sns.scatterplot(data=df.sample(3000, random_state=42),
                x="SKU_Quality", y="Price_USD", alpha=0.4)
plt.title("SKU_Quality vs Price"); plt.show()

"""###Feature Engineering"""

# ── Step 1 fix: force datetime conversion ─────────────────
print("Before:", df["Order_Datetime"].dtype)   # will show object

df["Order_Datetime"] = pd.to_datetime(
    df["Order_Datetime"],
    infer_datetime_format=True,   # handles mixed formats
    errors="coerce"               # bad rows → NaT instead of crash
)

def engineer_features(df):
    df = df.copy()

    # ── Datetime features ──────────────────────────────────
    df["order_hour"]      = df["Order_Datetime"].dt.hour
    df["order_dayofweek"] = df["Order_Datetime"].dt.dayofweek   # 0=Mon
    df["order_month"]     = df["Order_Datetime"].dt.month
    df["order_quarter"]   = df["Order_Datetime"].dt.quarter
    df["order_year"]      = df["Order_Datetime"].dt.year
    df["is_weekend"]      = df["order_dayofweek"].isin([5, 6]).astype(int)

    # ── Brand aggregations (fill NaN Brand_ID with -1) ────
    df["Brand_ID_filled"] = df["Brand_ID"].fillna(-1)
    brand_stats = df.groupby("Brand_ID_filled")["Price_USD"].agg(
        brand_avg_price="mean", brand_median_price="median"
    ).reset_index()
    df = df.merge(brand_stats, on="Brand_ID_filled", how="left")
    df["price_vs_brand_avg"] = df["Price_USD"] / (df["brand_avg_price"] + 1)

    # ── Category aggregations ─────────────────────────────
    cat_stats = df.groupby("Category")["Price_USD"].agg(
        category_median_price="median", category_price_std="std"
    ).reset_index()
    df = df.merge(cat_stats, on="Category", how="left")

    # ── Rarity scores (inverse frequency) ────────────────
    for col, new_col in [("Main_Gem",   "gem_rarity"),
                          ("Main_Metal", "metal_rarity"),
                          ("Main_Color", "color_rarity")]:
        freq = df[col].value_counts(normalize=True)
        df[new_col] = df[col].map(freq).fillna(freq.mean())
        df[new_col] = 1 / (df[new_col] + 1e-6)

    # ── Customer behaviour ────────────────────────────────
    cust_stats = df.groupby("User_ID").agg(
        customer_order_count=("Order_ID", "count"),
        customer_avg_spend=("Price_USD", "mean")
    ).reset_index()
    df = df.merge(cust_stats, on="User_ID", how="left")

    # ── Interaction features ──────────────────────────────
    df["metal_gem_combo"]   = (df["Main_Metal"].astype(str) + "_" +
                                df["Main_Gem"].astype(str))
    df["gender_category"]   = (df["Target_Gender"].astype(str) + "_" +
                                df["Category"].astype(str))
    df["metal_color_combo"] = (df["Main_Metal"].astype(str) + "_" +
                                df["Main_Color"].astype(str))

    # ── Target-encode high-cardinality combos (train only) ─
    # (applied later inside the split to avoid leakage)

    return df

df = engineer_features(df)
print(df.shape)
print(df.isnull().sum())

"""Feature Selection"""

from sklearn.feature_selection import mutual_info_regression
from sklearn.preprocessing     import LabelEncoder
from statsmodels.stats.outliers_influence import variance_inflation_factor

TARGET = "Price_USD"

# Columns to keep for modelling (drop raw IDs and datetime)
DROP_COLS = [
    "Order_Datetime", "Order_ID", "Product_ID", "User_ID",
    "Brand_ID", "Category_ID",          # replaced by engineered versions
    "Brand_ID_filled",                   # internal helper
    TARGET
]

feature_cols = [c for c in df.columns if c not in DROP_COLS]

# ── Encode objects for MI / VIF ───────────────────────────
df_enc = df[feature_cols + [TARGET]].copy()
df_enc.dropna(subset=[TARGET], inplace=True)

for col in df_enc.select_dtypes(include="object").columns:
    df_enc[col] = LabelEncoder().fit_transform(
        df_enc[col].astype(str)
    )

df_enc.fillna(df_enc.median(numeric_only=True), inplace=True)

X_sel = df_enc[feature_cols]
y_sel = df_enc[TARGET]

# ── Mutual Information ────────────────────────────────────
mi_scores = mutual_info_regression(X_sel, y_sel, random_state=42)
mi_df = (
    pd.Series(mi_scores, index=feature_cols)
    .sort_values(ascending=False)
)

print("Top 20 features by Mutual Information:")
print(mi_df.head(20))

mi_df.head(20).sort_values().plot(
    kind="barh", figsize=(9, 7),
    title="Mutual Information — Feature vs Price"
)
plt.tight_layout(); plt.show()

# ── VIF (drop constant/near-constant cols first) ──────────
X_for_vif = X_sel[[c for c in X_sel.columns
                    if X_sel[c].std() > 0]].copy()

def compute_vif(X):
    vif = pd.DataFrame({
        "feature": X.columns,
        "VIF": [variance_inflation_factor(X.values, i)
                for i in range(X.shape[1])]
    }).sort_values("VIF", ascending=False)
    return vif

vif_df = compute_vif(X_for_vif)
print("\nVIF scores:\n", vif_df)

low_vif = vif_df[vif_df["VIF"] < 10]["feature"].tolist()

# ── Final feature set: top-20 MI that also pass VIF ───────
top20_mi      = mi_df.head(20).index.tolist()
SELECTED_FEATURES = [f for f in top20_mi if f in low_vif]

# Always keep a few high-signal features even if correlated
MUST_KEEP = ["SKU_Quality", "brand_avg_price",
             "category_median_price", "gem_rarity", "metal_rarity"]
SELECTED_FEATURES = list(
    dict.fromkeys(MUST_KEEP + SELECTED_FEATURES)   # dedup, preserve order
)

print("\nFinal selected features:", SELECTED_FEATURES)

"""Preprocessing & Data Split"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing   import StandardScaler, OrdinalEncoder
from sklearn.impute          import SimpleImputer
from sklearn.pipeline        import Pipeline
from sklearn.compose         import ColumnTransformer

df_model = df[SELECTED_FEATURES + [TARGET]].dropna(subset=[TARGET]).copy()

# Log-transform target (right-skewed price → normal-ish)
df_model["log_price"] = np.log1p(df_model[TARGET])

X = df_model[SELECTED_FEATURES]
y = df_model["log_price"]

# 70 / 15 / 15 split
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42
)

print(f"Train: {X_train.shape} | Val: {X_val.shape} | Test: {X_test.shape}")

# ── Identify numeric vs categorical columns ───────────────
num_features = X.select_dtypes(include=["number"]).columns.tolist()
cat_features = X.select_dtypes(include=["object", "category"]).columns.tolist()

print("Numeric features :", num_features)
print("Categorical features:", cat_features)

# ── Pipelines ─────────────────────────────────────────────
num_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler",  StandardScaler()),
])

cat_pipe = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OrdinalEncoder(
        handle_unknown="use_encoded_value",
        unknown_value=-1
    )),
])

preprocessor = ColumnTransformer([
    ("num", num_pipe, num_features),
    ("cat", cat_pipe, cat_features),
])

X_train_pp = preprocessor.fit_transform(X_train)
X_val_pp   = preprocessor.transform(X_val)
X_test_pp  = preprocessor.transform(X_test)

print("Preprocessed train shape:", X_train_pp.shape)

"""Model Benchmarking"""

from sklearn.ensemble     import RandomForestRegressor
from sklearn.linear_model import Ridge
from xgboost              import XGBRegressor
from lightgbm             import LGBMRegressor
from sklearn.metrics      import (mean_squared_error,
                                   mean_absolute_error, r2_score)

def evaluate(name, y_true_log, y_pred_log):
    y_true = np.expm1(y_true_log)
    y_pred = np.expm1(y_pred_log)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae  = mean_absolute_error(y_true, y_pred)
    r2   = r2_score(y_true, y_pred)
    mape = np.mean(np.abs((y_true - y_pred) / (y_true + 1e-8))) * 100
    print(f"{name:25s} | RMSE: ${rmse:8.2f} | MAE: ${mae:7.2f} "
          f"| R²: {r2:.4f} | MAPE: {mape:.2f}%")
    return {"RMSE": rmse, "MAE": mae, "R2": r2, "MAPE": mape}

models = {
    "Ridge":        Ridge(alpha=1.0),
    "RandomForest": RandomForestRegressor(
                        n_estimators=200, n_jobs=-1,
                        random_state=42),
    "XGBoost":      XGBRegressor(
                        n_estimators=300, learning_rate=0.05,
                        random_state=42, tree_method="hist"),
    "LightGBM":     LGBMRegressor(
                        n_estimators=300, learning_rate=0.05,
                        random_state=42, verbose=-1),
}

results       = {}
fitted_models = {}

print("── Validation Performance ──────────────────────────")
for name, model in models.items():
    model.fit(X_train_pp, y_train)
    preds = model.predict(X_val_pp)
    results[name]       = evaluate(name, y_val, preds)
    fitted_models[name] = model

best_name  = min(results, key=lambda k: results[k]["RMSE"])
best_model = fitted_models[best_name]
print(f"\nBest model on validation set: {best_name}")

# ── Comparison bar chart ──────────────────────────────────
res_df = pd.DataFrame(results).T
res_df[["RMSE","MAE"]].plot(
    kind="bar", figsize=(10, 5),
    title="Model Comparison — RMSE & MAE (USD)"
)
plt.xticks(rotation=0); plt.tight_layout(); plt.show()

!pip install optuna-integration[lightgbm]

import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial):
    params = {
        "n_estimators":      trial.suggest_int("n_estimators", 200, 1000),
        "learning_rate":     trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        "max_depth":         trial.suggest_int("max_depth", 3, 12),
        "num_leaves":        trial.suggest_int("num_leaves", 20, 300),
        "min_child_samples": trial.suggest_int("min_child_samples", 10, 100),
        "subsample":         trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree":  trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha":         trial.suggest_float("reg_alpha", 1e-4, 10.0, log=True),
        "reg_lambda":        trial.suggest_float("reg_lambda", 1e-4, 10.0, log=True),
        "random_state": 42, "verbose": -1,
    }
    model = LGBMRegressor(**params)
    model.fit(
        X_train_pp, y_train,
        eval_set=[(X_val_pp, y_val)],
        callbacks=[
            optuna.integration.LightGBMPruningCallback(trial, "l2"),
        ]
    )
    val_preds = model.predict(X_val_pp)
    return np.sqrt(mean_squared_error(y_val, val_preds))

study = optuna.create_study(
    direction="minimize",
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=10)
)
study.optimize(objective, n_trials=60, show_progress_bar=True)

print("\nBest RMSE (log scale):", round(study.best_value, 6))
print("Best params:", study.best_params)

# ── Train final model on train+val ────────────────────────
X_trainval_pp = np.vstack([X_train_pp, X_val_pp])
y_trainval    = pd.concat([y_train, y_val])

final_model = LGBMRegressor(**study.best_params, verbose=-1)
final_model.fit(X_trainval_pp, y_trainval)

# ── Hold-out test evaluation ──────────────────────────────
test_preds_log = final_model.predict(X_test_pp)
print("\n── Final Model — Hold-out Test Set ─────────────────")
evaluate("LightGBM (tuned)", y_test, test_preds_log)

# ── Residual plot ─────────────────────────────────────────
y_test_orig = np.expm1(y_test)
y_pred_orig = np.expm1(test_preds_log)
residuals   = y_test_orig - y_pred_orig

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].scatter(y_pred_orig, residuals, alpha=0.2, s=8)
axes[0].axhline(0, color="red", linestyle="--")
axes[0].set_xlabel("Predicted Price (USD)")
axes[0].set_ylabel("Residual (USD)")
axes[0].set_title("Residuals vs Predicted")

axes[1].scatter(y_test_orig, y_pred_orig, alpha=0.2, s=8)
mn, mx = y_test_orig.min(), y_test_orig.max()
axes[1].plot([mn, mx], [mn, mx], "r--")
axes[1].set_xlabel("Actual Price"); axes[1].set_ylabel("Predicted Price")
axes[1].set_title("Actual vs Predicted")
plt.tight_layout(); plt.show()

import shap

feature_names_out = num_features + cat_features

explainer   = shap.TreeExplainer(final_model)
shap_values = explainer.shap_values(X_test_pp)

# ── 1. Global summary (beeswarm) ──────────────────────────
plt.figure(figsize=(10, 8))
shap.summary_plot(
    shap_values, X_test_pp,
    feature_names=feature_names_out,
    show=False
)
plt.title("SHAP Summary — What Drives Jewelry Price?")
plt.tight_layout(); plt.show()

# ── 2. Global bar (mean |SHAP|) ───────────────────────────
shap.summary_plot(
    shap_values, X_test_pp,
    feature_names=feature_names_out,
    plot_type="bar", show=False
)
plt.title("Global Feature Importance (Mean |SHAP|)")
plt.tight_layout(); plt.show()

# ── 3. Waterfall for a single prediction ─────────────────
for idx in [0, 10, 50]:          # explain 3 sample orders
    exp = shap.Explanation(
        values=shap_values[idx],
        base_values=explainer.expected_value,
        data=X_test_pp[idx],
        feature_names=feature_names_out
    )
    print(f"\nOrder index {idx} — "
          f"Actual: ${np.expm1(y_test.iloc[idx]):.2f} | "
          f"Predicted: ${np.expm1(test_preds_log[idx]):.2f}")
    shap.waterfall_plot(exp)

# ── 4. Dependence plots for top 3 features ────────────────
top3 = (
    pd.Series(np.abs(shap_values).mean(axis=0),
              index=feature_names_out)
    .sort_values(ascending=False)
    .head(3).index.tolist()
)
for feat in top3:
    shap.dependence_plot(feat, shap_values, X_test_pp,
                         feature_names=feature_names_out)

# ── 5. Business analyst summary table ────────────────────
mean_shap = pd.DataFrame({
    "feature":   feature_names_out,
    "mean_shap": np.abs(shap_values).mean(axis=0),
    "direction": pd.Series(np.sign(shap_values.mean(axis=0))).map(
                     {1.0: "↑ increases price",
                     -1.0: "↓ decreases price",
                      0.0: "neutral"}
                 )
}).sort_values("mean_shap", ascending=False)

print("\n── Business Analyst Summary ─────────────────────────")
print(mean_shap.head(15).to_string(index=False))

import joblib

def predict_price(product_dict: dict,
                  model, preprocessor,
                  feature_cols: list,
                  ci_percentiles=(10, 90)) -> dict:
    """
    Returns optimal price + confidence interval for a jewelry item.

    Parameters
    ----------
    product_dict : dict  — feature values (engineered features included)
    ci_percentiles : tuple — lower/upper % for confidence interval

    Returns
    -------
    dict with predicted price, recommended range, and key drivers
    """
    row    = pd.DataFrame([product_dict])[feature_cols]
    row_pp = preprocessor.transform(row)

    pred_log   = model.predict(row_pp)[0]
    pred_price = round(np.expm1(pred_log), 2)

    # CI via leaf-node variance across LightGBM trees
    leaf_preds = np.array([
        np.expm1(est.predict(row_pp)[0])
        for est in model.estimators_   # works for RF; for LGBM use below
    ]) if hasattr(model, "estimators_") else None

    if leaf_preds is not None:
        ci_low  = round(np.percentile(leaf_preds, ci_percentiles[0]), 2)
        ci_high = round(np.percentile(leaf_preds, ci_percentiles[1]), 2)
    else:
        # LightGBM fallback: ±15% around prediction
        ci_low  = round(pred_price * 0.85, 2)
        ci_high = round(pred_price * 1.15, 2)

    return {
        "predicted_price_usd":   pred_price,
        "recommended_min_usd":   ci_low,
        "recommended_max_usd":   ci_high,
        "confidence_interval":   f"P{ci_percentiles[0]}–P{ci_percentiles[1]}",
    }

# ── Example call ──────────────────────────────────────────
sample_product = {
    "SKU_Quality":           3,
    "order_hour":            14,
    "order_dayofweek":       2,
    "order_month":           11,
    "order_quarter":         4,
    "order_year":            2023,
    "is_weekend":            0,
    "brand_avg_price":       250.0,
    "brand_median_price":    200.0,
    "price_vs_brand_avg":    1.0,
    "category_median_price": 180.0,
    "category_price_std":    90.0,
    "gem_rarity":            5.2,
    "metal_rarity":          2.1,
    "color_rarity":          1.8,
    "customer_order_count":  4,
    "customer_avg_spend":    220.0,
    "Category":              "ring",
    "Main_Metal":            "gold",
    "Main_Gem":              "diamond",
    "Target_Gender":         "Female",
    "Main_Color":            "yellow",
    "metal_gem_combo":       "gold_diamond",
    "gender_category":       "Female_ring",
    "metal_color_combo":     "gold_yellow",
}

result = predict_price(
    sample_product, final_model,
    preprocessor, SELECTED_FEATURES
)
print("\n── Price Recommendation ─────────────────────────────")
for k, v in result.items():
    print(f"  {k:28s}: {v}")

# ── Persist artefacts ─────────────────────────────────────
joblib.dump(final_model,       "jewelry_price_model.pkl")
joblib.dump(preprocessor,      "jewelry_preprocessor.pkl")
joblib.dump(SELECTED_FEATURES, "selected_features.pkl")
print("\nAll artefacts saved successfully.")

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Best parameters dictionary
best_params = {
    'n_estimators': 842,
    'learning_rate': 0.1685,
    'max_depth': 9,
    'num_leaves': 258,
    'min_child_samples': 43,
    'subsample': 0.9744,
    'colsample_bytree': 0.9632,
    'reg_alpha': 0.0222,
    'reg_lambda': 0.0018
}

# Best RMSE
best_rmse = 0.017715

# Convert to DataFrame
df = pd.DataFrame({
    'Parameter': list(best_params.keys()),
    'Value': list(best_params.values())
})

# Create figure
plt.figure(figsize=(12, 6))

# Bar chart
bars = plt.bar(df['Parameter'], df['Value'])

# Add value labels
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        height,
        f'{height:.4f}',
        ha='center',
        va='bottom',
        fontsize=9
    )

# Title and labels
plt.title(f'Best Hyperparameters from Optimization\nBest RMSE (log scale): {best_rmse:.6f}')
plt.xlabel('Hyperparameters')
plt.ylabel('Values')

# Rotate x labels
plt.xticks(rotation=45)

# Layout
plt.tight_layout()

# Show plot
plt.show()

